apiVersion: apps/v1
kind: Deployment

metadata:
  name: cloud-dashboard

spec:
  replicas: 2

  selector:
    matchLabels:
      app: cloud-dashboard

  template:
    metadata:
      labels:
        app: cloud-dashboard

    spec:
      containers:
        - name: cloud-dashboard
          image: cloud-dashboard:v2
          imagePullPolicy: Never

          ports:
            - containerPort: 80

          livenessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 5
            periodSeconds: 10

          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 2
            periodSeconds: 5

          resources:
            requests:
              cpu: "100m"
              memory: "64Mi"
            limits:
              cpu: "200m"
              memory: "128Mi"

          volumeMounts:
            - name: nginx-config
              mountPath: /etc/nginx/conf.d/default.conf
              subPath: default.conf

      volumes:
        - name: nginx-config
          configMap:
            name: cloud-dashboard-config